

# This file was *autogenerated* from the file task备份.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_255 = Integer(255); _sage_const_19 = Integer(19); _sage_const_0 = Integer(0); _sage_const_486662 = Integer(486662); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8)#!/use/bin/env sage

from sys import exit
from hashlib import sha256


FLAG = b"SYC{123321123}"

ec = EllipticCurve(GF(_sage_const_2 **_sage_const_255 -_sage_const_19 ), [_sage_const_0 , _sage_const_486662 , _sage_const_0 , _sage_const_1 , _sage_const_0 ])
# //Curve25519
p = ec.order()
ZmodP = Zmod(p)
G = ec.lift_x(_sage_const_9 )

# 如果是point就把xy相乘
ha = lambda x: x if isinstance(x, int) or isinstance(x, Integer) else product(x.xy())
hashs = lambda *x: int.from_bytes(sha256(b'.'.join([b'%X' % ha(x) for x in x])).digest(), 'little') % p


def hashp(x):
    x = hashs((x))
    while True:
        try:
            return ec.lift_x(x)
        except:
            x = hashs((x))


def keygen():
    x = randint(_sage_const_1 , p-_sage_const_1 )
    P = x * G
    return x, P


def verify(signature, P, m):
    I, e, s = signature
    return e == hashs(m, s*G + e*P, s*hashp(P) + e*I)


if __name__ == "__main__":
    x, P = keygen()
    m = randint(_sage_const_1 , p-_sage_const_1 )
    print(x, P, m)

    spent = set()
    for i in range(_sage_const_8 ):
        Ix = int(input('I (x): '))
        Iy = int(input('I (y): '))
        I = ec(Ix, Iy)
        e = int(input('e: '))
        s = int(input('s: '))
        if verify((I, e, s), P, m) and I not in spent:
            print('ok')
            spent.add(I)
        else:
            print('nope')
            exit(_sage_const_1 )

    print(FLAG)

