

# This file was *autogenerated* from the file task.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_255 = Integer(255); _sage_const_19 = Integer(19); _sage_const_0 = Integer(0); _sage_const_486662 = Integer(486662); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8)#!/use/bin/env sage
from icecream import *
from sys import exit
from hashlib import sha256
from Crypto.Util.number import *

FLAG = b"SYC{123321123}"

ec = EllipticCurve(GF(_sage_const_2 **_sage_const_255 -_sage_const_19 ), [_sage_const_0 , _sage_const_486662 , _sage_const_0 , _sage_const_1 , _sage_const_0 ])
p = ec.order()
ZmodP = Zmod(p)
G = ec.lift_x(_sage_const_9 )

ha = lambda x: product(x.xy()) if type(x)==type(G) else x
hashs = lambda *x: int.from_bytes(sha256(b'.'.join([b'%X' % ha(x) for x in x])).digest(), 'little') % p


def hashp(x):
    x = hashs((x))
    while True:
        try:
            return ec.lift_x(x)
        except:
            x = hashs((x))


def keygen():
    x = randint(_sage_const_1 , p-_sage_const_1 )
    P = x * G
    return x, P


def verify(signature, P, m):
    I, e, s = signature
    tmp = hashs(m, s*G + e*P, s*hashp(P) + e*I)
    return e == tmp

menu="""
[1] log in
[2] gifts to you :-)
[3] get secret"""

if __name__ == "__main__":
    m = randint(_sage_const_1 , p-_sage_const_1 )
    x, P = keygen()
    spent = set()
    while _sage_const_1 :
        print(menu)
        op = input('>')
        if(op=='1'):
            
            Ix = int(input('I (x): '))
            Iy = int(input('I (y): '))
            I = ec(Ix, Iy)
            e = int(input('e: '))
            s = int(input('s: '))
            
            if verify((I, e, s), P, m) and I not in spent:
                print('ok')
                spent.add(I)
            else:
                print('nope')
        if(op=='2'):
            print(x, P,m)
        if(op=='3'):
            print(f'Completion:{len(spent)}/8')
            if(len(spent)==_sage_const_8 ):
                print('You have a great understanding on signature !')
                print(FLAG)
            else:
                print('You don\'t have enough permissions')
    

