

# This file was *autogenerated* from the file /mnt/c/Users/16953/Desktop/密码学归档/mmxctf/赛题归档/crypto-challenges/L3HCTF2021/EzECDSA/LLL.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 = Integer(0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141); _sage_const_256 = Integer(256); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_102 = Integer(102); _sage_const_100 = Integer(100); _sage_const_101 = Integer(101)#! /usr/bin/sage

from tqdm import tqdm
from rich.progress import track
from rich.traceback import install
install()
# -----------------------------------
from data import *
# from sage.all import *
from libnum import invmod

# from Crypto.Util.number import *
n = _sage_const_0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 
tt=[]
uu =[]
for i in range(len(ss)):
    tt.append(rr[i]*invmod(_sage_const_256 *ss[i],n))
    uu.append(hh[i]*invmod(_sage_const_256 *ss[i],n))
l=_sage_const_8 
print('ok')

ct = _sage_const_1 /(_sage_const_2 **l)
cu = n/(_sage_const_2 **l)
print(ct)
print( cu)
M = [[_sage_const_0  for i in range(_sage_const_102 )] for j in range(_sage_const_102 )]
for i in range(_sage_const_100 ):
    for j in range(_sage_const_100 ):
        M[i][j] = n
for i in range(_sage_const_100 ):
    M[_sage_const_100 ][i] = tt[i]
    M[_sage_const_101 ][i] = uu[i]
M[_sage_const_100 ][_sage_const_100 ] = ct
M[_sage_const_101 ][_sage_const_101 ] = cu
M = matrix(M)
print('start LLLing.....')
B = M.LLL()
# A = matrix([[1,2,3],[1,2,3],[1,2,34]])
# A.LLL()
f = open('./data','w+')
for i in B:
    f.write(str(list(i))+'\n')

