

# This file was *autogenerated* from the file /mnt/c/Users/16953/Desktop/L3HCTF/LLL.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 = Integer(0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_102 = Integer(102); _sage_const_1 = Integer(1); _sage_const_256 = Integer(256); _sage_const_32 = Integer(32)#! /usr/bin/sage
from sage.all import *
from sage.groups.generic import bsgs
from Crypto.Util.number import *
from libnum import invmod
from data import *
n = _sage_const_0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 
l=_sage_const_8 
LEN=len(a)
tt=[]
uu=[]
for i in range(len(a)):
    tmp1 = (r[i]*invmod(s[i]*_sage_const_2 **l,n))%n
    tt.append(tmp1)
    tmp2 = ((a[i]*s[i]-H[i])*invmod(s[i]*_sage_const_2 **l,n))%n
    uu.append(tmp2)
M=[[_sage_const_0  for i in range(_sage_const_102 )] for j in range(_sage_const_102 )]

for i in range(LEN):
    M[i][i]=n
for i in range(LEN):
    M[LEN][i]=tt[i]
    M[LEN+_sage_const_1 ][i]=uu[i]

ct= _sage_const_2 **_sage_const_256 
cu= _sage_const_2 **_sage_const_32  
M[LEN][LEN]=ct
M[LEN+_sage_const_1 ][LEN+_sage_const_1 ]=cu
print(ct)
print(cu)
print("start LLL....")
M = matrix(M)
M = [list(i) for i in M]
fr=open('./output','w')
for row in M:
    # if(ct in row[-1]):
    print(row,file=fr)
fr.close()

