

# This file was *autogenerated* from the file 123.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10000000000000001119 = Integer(10000000000000001119); _sage_const_0 = Integer(0); _sage_const_24 = Integer(24); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1)
from itertools import product
import struct
from random import SystemRandom
p = _sage_const_10000000000000001119 

K = GF(p)
R = K['x']; (x,) = R._first_ngens(1); y=x
f = y + prod(map(eval, 'yyyyyyy'))
C = HyperellipticCurve(f, _sage_const_0 )
J = C.jacobian()

def get_u_from_out(output, known_input):
    res = []
    for i in range(_sage_const_24 ):
        res.append(output[i]^known_input[i])
    res = bytes(res)
    u0, u1, u2 = struct.unpack("<QQQ", res)
    u = x**_sage_const_3 +x**_sage_const_2 *u2+x*u1+u0
    return u


def get_v_from_u(u):
    Kbar = GF(p**_sage_const_6 )
    Rbar = Kbar["t"]; (t,) = Rbar._first_ngens(1)
    u2 = u.change_ring(Rbar)
    roots = [x[_sage_const_0 ] for x in u2.roots()]
    ys = []
    for root in roots:
        ys.append(f(root).sqrt(_sage_const_0 ,_sage_const_1 ))
    res = []
    for perm in product(range(_sage_const_2 ), repeat=_sage_const_3 ):
        poly = Rbar.lagrange_polynomial([(roots[i], ys[i][perm[i]]) for i in range(_sage_const_3 )])
        if poly[_sage_const_0 ] in K:
            res.append(R(poly))
    return res

def try_decode(output, u, v):
    rs = [u[_sage_const_0 ], u[_sage_const_1 ], u[_sage_const_2 ], v[_sage_const_0 ], v[_sage_const_1 ], v[_sage_const_2 ]]
    otp = struct.pack("<QQQQQQ", *rs)
    plain = []
    for i in range(len(output)):
        plain.append(output[i]^otp[i])
    return bytes(plain)


# output = bytes.fromhex("a0955c882185b50a69d9d19a24778519d6da23894e667d7130b495b645caac72163d242923caa00af845f25890")
# known_input = b"Hello! The flag is: hxp{"
# u = get_u_from_out(output, known_input)
# vs = get_v_from_u(u)
# print('-------------')
# print(u,vs)
# print('-------------')
# for v in vs:
#     print(try_decode(output,u,v))


output2 = bytes.fromhex("fca3dd468e9f6f0e5e70046af7a6e4355fd8b15f8523980933dd9d1385884929fd0a67517c30fa7af82c07c45769d5216dd5721898f1c219c4753021b7f1bc6db2ee5c450a9efa4da6c40df913fb113bcd5193ba3135351e55db3ba23c")
known_input = b"Hello! The flag is: hxp{"
# known_input = b"aaaaaaaaaaaaaaaaaaaaflag"
u = get_u_from_out(output2, known_input)
vs = get_v_from_u(u)
print('-------------')
print(u,vs)
print('-------------')

for v in vs:
    print(try_decode(output2, u, v))

# v = vs[0]
# Q = J(u,v)


