

# This file was *autogenerated* from the file EXP.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10000000000000001119 = Integer(10000000000000001119); _sage_const_8456637504717104773 = Integer(8456637504717104773); _sage_const_644133729621365327 = Integer(644133729621365327); _sage_const_7060694052512827322 = Integer(7060694052512827322); _sage_const_4881556192156233109 = Integer(4881556192156233109); _sage_const_7367516523653099255 = Integer(7367516523653099255); _sage_const_6746795449489230423 = Integer(6746795449489230423); _sage_const_24069496990635245 = Integer(24069496990635245); _sage_const_2569299995974183471 = Integer(2569299995974183471); _sage_const_5990686822681667460 = Integer(5990686822681667460); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_11 = Integer(11); _sage_const_22 = Integer(22); _sage_const_33 = Integer(33)
output2 = bytes.fromhex("66def695b20eeae3141ea80240e9bc7138c8fc5aef20532282944ebbbad76a6e17446e92de5512091fe81255eb34a0e22a86a090e25dbbe3141aff0542f5")
M=IntegerModRing(p+_sage_const_1 )
p = _sage_const_10000000000000001119 
A=Matrix(M,[[_sage_const_8456637504717104773 , _sage_const_644133729621365327 , _sage_const_7060694052512827322 ],
[_sage_const_4881556192156233109 , _sage_const_7367516523653099255 , _sage_const_6746795449489230423 ], 
[_sage_const_24069496990635245 , _sage_const_2569299995974183471 , _sage_const_5990686822681667460 ]])
b=vector(M,[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ])
ee=A.solve_right(b)
e0, e1, e2 = ZZ(ee[_sage_const_0 ]), ZZ(ee[_sage_const_1 ]), ZZ(ee[_sage_const_2 ])

D0, D1, D2 = [J(C(x, min(f(x).sqrt(_sage_const_0 ,_sage_const_1 )))) for x in (_sage_const_11 ,_sage_const_22 ,_sage_const_33 )]
assert e0*D0+e1*D1+e2*D2 == Q
otp1 = struct.pack("<QQQQQQ", *[u[_sage_const_0 ],u[_sage_const_1 ],u[_sage_const_2 ],v[_sage_const_0 ],v[_sage_const_1 ],v[_sage_const_2 ]])

uu, vv = e0**_sage_const_2 *D0+e1**_sage_const_2 *D1+e2**_sage_const_2 *D2
otp2 = struct.pack("<QQQQQQ", *[uu[_sage_const_0 ],uu[_sage_const_1 ],uu[_sage_const_2 ],vv[_sage_const_0 ],vv[_sage_const_1 ],vv[_sage_const_2 ]])
otp = otp1+otp2
flag = ""
for i in range(len(output2)):
    flag += chr(otp[i]^output2[i])
print(flag)
'''
(x^3 + 4986131889746979161*x^2 + 1215277151449350005*x + 9406735202825780999,

    6739280444476523560*x^2 + 4418166319852619578*x + 8255796342084066913, 
    3)
'''

