

# This file was *autogenerated* from the file exp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_144 = Integer(144)
import pickle
data = pickle.load(open('enc.pickle', 'rb'))
cip = data['cip']
pbkey = data['pbkey']
print(len(pbkey))


S = cip
M = pbkey

n = len(M)
L = matrix.zero(n + _sage_const_1 )

for row, x in enumerate(M):
    L[row, row] = _sage_const_2 
    L[row, -_sage_const_1 ] = x

L[-_sage_const_1 , :] = _sage_const_1 
L[-_sage_const_1 , -_sage_const_1 ] = S
f = open('LLLdata.txt','a+')
res = L.LLL()
for i in range(_sage_const_144 ):
    ans = list(res[i])
    
    f.write(str(ans)+'\n')
    print(ans)


