

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_11209 = Integer(11209); _sage_const_48 = Integer(48); _sage_const_1185157 = Integer(1185157); _sage_const_864 = Integer(864); _sage_const_0 = Integer(0); _sage_const_191 = Integer(191); _sage_const_12 = Integer(12); _sage_const_65 = Integer(65); _sage_const_9 = Integer(9); _sage_const_637231263346693346010600868176842100660564986054619857 = Integer(637231263346693346010600868176842100660564986054619857); _sage_const_81086401756297731072425447670017660116155468002441526 = Integer(81086401756297731072425447670017660116155468002441526); _sage_const_29400417578654041653688375863673590665042836425148365175935874356653994350305605 = Integer(29400417578654041653688375863673590665042836425148365175935874356653994350305605); _sage_const_6284274674391913738225458829167585075352347781720125288787017561681121629385876 = Integer(6284274674391913738225458829167585075352347781720125288787017561681121629385876); _sage_const_95 = Integer(95); _sage_const_277 = Integer(277); _sage_const_91 = Integer(91); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1)
from fractions import Fraction as Frac
from icecream import *

R = QQ['x, y, z']; (x, y, z,) = R._first_ngens(3)
# n=4
F = x**_sage_const_3  + y**_sage_const_3  + z**_sage_const_3  - _sage_const_3 *x**_sage_const_2 *(y+z) - _sage_const_3 *y**_sage_const_2 *(z+x) - _sage_const_3 *z**_sage_const_2 *(x+y) - _sage_const_5 *x*y*z

# n=6
#   x^3 - 5*x^2*y - 5*x^2*z - 5*x*y^2 - 9*x*y*z - 5*x*z^2 + y^3 - 5*y^2*z -5*y*z^2 + z^3

f, g = WeierstrassForm(F)

f, g = (-_sage_const_11209 /_sage_const_48 , _sage_const_1185157 /_sage_const_864 )
E = EllipticCurve([_sage_const_0 , _sage_const_0 , _sage_const_0 , f, g])
P = (-_sage_const_191 /_sage_const_12 , _sage_const_65 /_sage_const_2 )
P = E(P)
print(_sage_const_9 *P)

print('===================================')

x9P = _sage_const_637231263346693346010600868176842100660564986054619857 /_sage_const_81086401756297731072425447670017660116155468002441526 

y9p = _sage_const_29400417578654041653688375863673590665042836425148365175935874356653994350305605 /_sage_const_6284274674391913738225458829167585075352347781720125288787017561681121629385876 

a = x9P
b = y9p

A = [[-_sage_const_95 /_sage_const_2 , -_sage_const_95 /_sage_const_2 , _sage_const_277 /_sage_const_12 ],
     [-_sage_const_91 /_sage_const_2 ,  _sage_const_91 /_sage_const_2 ,      _sage_const_0 ],
     [-_sage_const_6 ,       -_sage_const_6 ,      _sage_const_1 ]
     ]

B = [
    [a],
    [b],
    [_sage_const_1 ]
]
B = Matrix(B)
m = Matrix(A)
inv_m = m**(-_sage_const_1 )
# print(inv_m)

x = inv_m*B
x1 = x[_sage_const_0 ][_sage_const_0 ]
x2 = x[_sage_const_1 ][_sage_const_0 ]
x3=x[_sage_const_2 ][_sage_const_0 ]

t = lcm(x1.denominator(), lcm(x2.denominator(), x3.denominator()))
print(-x1*t)
print(-x2*t)
print(-x3*t)


